name: tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
          cache: gradle
      - name: Build
        run: ./gradlew build
      - name: Test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: check
